### ISSUE TITLE
Expand personal information input area beyond email address

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#104]
1. name
2. e-mail address
3. user type (which best describes you)
4. organizational affiliation, if any

after transitland/transitland-datastore#258

**Comment by drewda** [comment]
all fields will be optional

**Comment by souperneon** [comment]
add language in the blurb to say everything is optional and remove 'optional' from the field labels

**Comment by drewda** [comment]
user types:

- community builder
- data enthusiast
- app developer
- hardware vendor
- consultant
- transit agency staff
- other public official

**Comment by drewda** [comment]
@meghanhade, @souperneon, @rmglennon: here are what my additions look like. We can improve copy after merging. (Using the name of the top federal transit official in the country might be a bit too clever.) Any functionality or UX concerns before merging?

<img width="960" alt="feed_registry_ _transitland" src="https://cloud.githubusercontent.com/assets/212369/12681246/74d0765c-c662-11e5-8f85-0726df3305e1.png">

**Comment by meghanhade** [comment]
@drewda the UI looks good. I'd take out the "optional" after each field label and incorporate that into the instruction text. I'd also take out "user type" and just say "which best describes you?", "what brings your here" or something along those lines.

**Comment by meghanhade** [comment]
@drewda but also, we can make those changes separately if you want to merge! Just remembered we talked about looking at the copy separately, once you had the structure in place.

**Comment by souperneon** [comment]
I'm just going to join this party! WE can make this shorter by putting name and email on the same line. And 'what best describes you' and 'affiliation' on the second line (in that order)

**Comment by rmglennon** [comment]
Joining the party, too, but I have a more general question about the hint text. With these questions, I don't think it's necessary.

Also kind of wondering about using it on some of the other forms?
https://www.nngroup.com/articles/form-design-placeholders/

**Comment by drewda** [comment]
I'll put name and e-mail on the same line, reorder the second row, @meghanhade can merge, and then you all can edit copy.

**Comment by drewda** [comment]
@meghanhade this is now ready for you to merge
