### ISSUE TITLE
Create mock for entrance to 'add a feed' flow at the bottom of the feed registry

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#105]

**Comment by mjcunningham** [comment]
Use same style as bottom of mapzen docs section

**Comment by souperneon** [comment]
![contribute](https://cloud.githubusercontent.com/assets/6125224/12650071/6549142c-c5af-11e5-97aa-a4aa8ca955fe.png)

Something like ^^ (ignore the dumb button)

**Comment by souperneon** [comment]
![screen shot 2016-02-02 at 11 38 27 am](https://cloud.githubusercontent.com/assets/6125224/12756650/b021b336-c9a2-11e5-9fcf-113683e1e307.png)
