### ISSUE TITLE
before submitting a feed, user must agree to contributor agreement

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#119]
legal advice:

>
In terms of the actual form of consent, the ideal would be a box that only allows you to check it once you’ve read (or more likely just scrolled) through the ToS, paired with a “Submit” button.  If that’s enough of a pain that you think it would turn off users, a simple check box paired with a “Submit” button should be fine. 

Let's just have a checkbox that user must click to indicate agreement, before they're able to press submit button.

Link off to contributor agreement, either in a separate window or a modal. <-- have a preference, @souperneon or @meghanhade ?

**Comment by meghanhade** [comment]
I'd prefer a modal. We can set up the requirement for legal agreement the way it's set up to require inclusion of at least one operator in the changeset.

**Comment by drewda** [comment]
I'll put the current draft of the contributor license agreement text in Markdown on an issue in our private repo so you two can see its length.

**Comment by souperneon** [comment]
@hanbyul-here @meghanhade we can do it the same way we do developer login for mapzen.com. It has a checkbox and links to go look at the terms if one desires :)

**Comment by meghanhade** [comment]
@souperneon that sounds good to me.

**Comment by drewda** [comment]
Here's what the draft of the contributor agreement looks like: https://github.com/mapzen/transitland-internal/issues/1#issuecomment-173364687

**Comment by drewda** [comment]
@meghanhade @hanbyul-here @souperneon we now have the contributor agreement finalized. If you want it as HTML, open this comment for editing: https://github.com/mapzen/transitland-internal/issues/1#issuecomment-173364687 or if you'd prefer it as Markdown, let me know.

(FYI, I'm using [pandoc](http://pandoc.org/) on my computer to convert the lawyers' Word doc to Markdown, HTML, etc.)

**Comment by drewda** [comment]
add contributor agreement to marketing site: https://github.com/transitland/www-transit-land/issues/132
