### ISSUE TITLE
Adding this zip from Victoria, Australia causes a hang

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#121]
This feed from Victoria, Australia has a few issues with it, including subfolders, a zip that uses pkzip format, and being behind a checkbox. 

http://data.ptv.vic.gov.au/downloads/gtfs.zip

Home page for the operator's feed: https://www.data.vic.gov.au/data/dataset/ptv-timetable-and-geographic-information-2015-gtfs

Attempting to add it causes a hang when parsing the operators.

**Comment by drewda** [comment]
Will need support for nested zip files: https://github.com/transitland/transitland-datastore/issues/316
