### ISSUE TITLE
Pagination/infinite scroll for feed registry

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#122]
We need a solution to handle a long list in the Feed Registry.

**Comment by drewda** [comment]
@meghanhade if you'd like to see the way I added simple pagination to Dispatcher: https://github.com/transitland/dispatcher/commit/275aa47a0bae7f781f4248ec31a11f6814a1dc98 (although that may or may not be the way you want to code it and style it for Feed Registry)

**Comment by souperneon** [comment]
let's tackle this in in the future. Definitely no infinite scroll.
Might need to add search/filter functionality to the registry along with pagination

**Comment by drewda** [comment]
goes along with #127

**Comment by meghanhade** [comment]
@drewda could you please review PR https://github.com/transitland/feed-registry/pull/258?

**Comment by drewda** [comment]
@meghanhade sure, I just put a few small comments on the PR.
