### ISSUE TITLE
Sort operators on back end

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#127]
The feed registry table has sorting functionality, but because we'll be paginating results, this sorting needs to happen on the back end.

**Comment by drewda** [comment]
to go along with #122

**Comment by meghanhade** [comment]
Discussed this with @irees this afternoon, the api is already set up to accept a sorting param. We'll implement this this week.

**Comment by meghanhade** [comment]
See issue https://github.com/transitland/transitland-datastore/issues/440

**Comment by meghanhade** [comment]
@drewda PR https://github.com/transitland/feed-registry/pull/274/files is ready to go.
