### ISSUE TITLE
Existing feed/operator feedback

### ISSUE THREAD

**Issue by irees** [transitland/feed-registry#135]
Provide feedback if the feed, feed url, or operators already exist in datastore.

Backend: https://github.com/transitland/transitland-datastore/issues/471

**Comment by meghanhade** [comment]
@drewda @irees do we want to provide the feedback, but still allow the feed submission to go through? If the submission goes through, the submission will be a duplicate (at this time), correct?

**Comment by irees** [comment]
@meghanhade I think we should provide feedback that there is an existing feed or operator. A submitted changeset would be processed as an update to the existing records.

**Comment by drewda** [comment]
can go out with Datastore 4.7.5 https://github.com/transitland/transitland-datastore/pull/519
