### ISSUE TITLE
fix country count

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#137]
multiple countries in feed should cause the count to render as plural (countries).

**Comment by rmglennon** [comment]
While you're poking around @meghanhade , could you also change the word "agencies" to be "operators" next to the country count?

![image](https://cloud.githubusercontent.com/assets/4380498/12561399/e0eb5480-c354-11e5-8e82-34c487dd0730.png)

**Comment by meghanhade** [comment]
Good call, @rmglennon!
