### ISSUE TITLE
Increase width in feed registry table - state or province column

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#140]
Well, we fixed the text to make it more internationally friendly and globalized, but that caused the sort button to overlap...

![image](https://cloud.githubusercontent.com/assets/4380498/12562438/0711a4a2-c35a-11e5-896b-5860add9aa3a.png)

**Comment by hanbyul-here** [comment]
I disabled sorting icon on mobile, and wrapped the table with table-wrapper on mobile (so it scrolls horizontally)
