### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#149]
- [ ] Make the steps under the 'Add a transit feed' stand out more (see screenshot. I made the type size 18px and increased bottom padding to 5px and made left margin on the borders at the bottom to 20px)
![screen shot 2016-01-27 at 3 41 11 pm](https://cloud.githubusercontent.com/assets/6125224/12630952/f71ee75c-c51c-11e5-9e84-8b0c819e822c.png)

- [ ] Make Blurb above forms 16px (at least) and #333 like other text on the site
- [ ] Make Blurb above forms the same container width as the form. Currently, its wider. Makes the line length too long
- [ ]  Style helper text around form fields as a caption style - like on step 2
- [ ] Make inactive/active states for buttons more obvious. Logic: button should turn blue when all the required fields are filled in by the user. Can also do dimmed down blue and bright blue to indicate the same. Currently, all buttons look inactive
- [ ] Make filled in text in form fields larger. Currently 16px, make it at least 18px so it contrasts with the label (see screenshot)
![screen shot 2016-01-27 at 5 38 03 pm](https://cloud.githubusercontent.com/assets/6125224/12630961/ff5d7c44-c51c-11e5-8075-2c27945bced2.png)
- [ ]  Change '<' to one from fontawesome (we use that on mapzen.com)
- [ ] Back button should just say 'back'

**Step 1**
- [ ] Make the URL more fake (http://www.transitagency.com/feeds/samplefeed.zip)
- [ ]  Add error message for when user does not fill out the URL field
- [ ]  Remove 'Cancel' button from this step

**Step 2**
- [ ]  Is there no 'back' button here? I know the user can lose all changes, but it can be disorienting if the back doesn't appear at all

**Step 3**
- [ ]  Nothing should be selected on this step. Currently, 'no' is selected. We can fake it if we want.
- [ ]  Make 'yes' button be green #67A53F (from the feed registry icons).Yellow is a warning state color.
- [ ]  Make 'no' button be 'red' #AD2129 (from the feed registry icons)

**Step 4**
- [ ] Maybe we can make the text have some hierarchy here. Separate the thank you from what's next

**Comment by souperneon** [comment]
@meghanhade @hanbyul-here I'm creating this UI polish ticket with everything in the kitchen sink. I have more things to add but wanted to flag it you guys. Not all of these are high priority.

**Comment by meghanhade** [comment]
@souperneon :+1: thanks!

**Comment by meghanhade** [comment]
@souperneon @hanbyul-here for step #2, I have a separate ticket set up-- #157

**Comment by souperneon** [comment]
Closing this after creating separate issues for each item
