### ISSUE TITLE
Add Feed flow - pages start off scrolled down and hide headers and intro text

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#151]
I tested on Chrome (Mac), Firefox 44 (Mac), Safari, and Microsoft Edge (Windows 10). Although the extent of the vertical scroll was different across the browsers, they generally all cut off some of the text at the top of the page.

It starts because the Feed Registry page is already scrolled down to get to the Add Feed button. If I scroll up on the first page of the wizard, it sticks throughout.

Here's what I see in Firefox, for example. 

![image](https://cloud.githubusercontent.com/assets/4380498/12631738/e53a43a2-c507-11e5-93d0-755c8da731c7.png)

**Comment by meghanhade** [comment]
@rmglennon thanks for adding a ticket on this. We've discussed but hadn't added a ticket yet--thanks!

**Comment by drewda** [comment]
@meghanhade here's a really simple approach I tried on Dispatcher: https://github.com/transitland/dispatcher/blob/master/app/application/route.js Always takes user to the top, with no memory for scroll position.

**Comment by meghanhade** [comment]
@drewda  I found a scrolling solution--https://github.com/transitland/feed-registry/pull/161
