### ISSUE TITLE
Typo on step 4 of add a feed

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#152]
'notfied' in the blurb section above the form

**Comment by rmglennon** [comment]
Two other little things:
[ ] License page: Make the paragraph at the top as wide as the box. It currently flows to page width.
[ ] Success page: Add a couple of line breaks with empty lines so the text is more scannable. Perhaps a blank line between Thanks for submitting and Next, and another one between "...posting on Transitland." and "If you provided contact info..."
![image](https://cloud.githubusercontent.com/assets/4380498/12656565/db51725a-c5b3-11e5-97f9-cc095e5bec16.png)

**Comment by souperneon** [comment]
:100:
