### ISSUE TITLE
review text link colors and buttons

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#155]
There are different colors and button styles all over. Let's consolidate text links and come up with a button style (like the playground) that we can use for the rest of the site

@meghanhade @hanbyul-here

**Comment by drewda** [comment]
Perhaps best handled separate from "add a feed", as part of a transit.land style guide instead.

**Comment by meghanhade** [comment]
@souperneon @drewda can we move this issue from 'add a feed' to style guide, or somewhere else?
