### ISSUE TITLE
stand-alone intro at beginning of feed step

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#159]
with links out to "How it Works", docs, and some other parts of Transitland. In case a user lands on this page without any context.

**Comment by drewda** [comment]
@rmglennon I've drafted an intro paragraph in the attached PR #191 Please feel free to make any and all revisions in the PR.

**Comment by rmglennon** [comment]
Reopening after some discussion with @souperneon and @meghanhade regarding the use case for this text. I'll take a quick run through the copy.

**Comment by rmglennon** [comment]
@souperneon @meghanhade Maybe start from this (hmm, wasn't there something before with GTFS definition pop-ups?)...

Transitland brings together many sources of transit data to build a [directory of operators and authoritative feeds](https://transit.land/feed-registry/) that can be edited by transit enthusiasts and developers. You can help expand Transitland's coverage throughout the world by submitting a feed.

Have a look at the [documentation](https://github.com/transitland/transitland-docs/blob/master/add-feed.md) to learn more about submitting a feed.

If you know of a feed, please continue below!

**Comment by meghanhade** [comment]
@rmglennon I like this. If @souperneon agrees, I'll push the changes.

**Comment by souperneon** [comment]
:+1:
