### ISSUE TITLE
Styling Steps

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#164]
Make the steps under the 'Add a transit feed' stand out more (see screenshot. I made the type size 18px and increased bottom padding to 5px and made left margin on the borders at the bottom to 20px)

![](https://cloud.githubusercontent.com/assets/6125224/12630952/f71ee75c-c51c-11e5-9e84-8b0c819e822c.png)

**Comment by souperneon** [comment]
https://github.com/transitland/feed-registry/issues/99

**Comment by meghanhade** [comment]
#99 is closed now, @hanbyul-here.
