### ISSUE TITLE
Review error states language

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#172]
Let's do this together. I think they can be more helpful

**Comment by meghanhade** [comment]
@rhonda @souperneon let's discuss this today?

**Comment by rmglennon** [comment]
OK! I can set up a quick chat.

**Comment by rmglennon** [comment]
Notes to self from meeting: invalid source exception - downloaded gtfs, but not valid gtfs; agency error

socket error - underlying network problem, couldn’t reach server at all (could be temporary or indefinite) - please check the URL and try again. If the URL is good, then it’s on the agency side

http server exception - reaches server, but server sends error code (whatever the http message) - e.to_s (ruby exceptions - override on front end with message). eg, 404, needed to log in/not authorized, etc. these are the standard html response code....these should now be returned.

standard error - could not download file (fallback error). unknown. Ian will improve this.

url does need to end in .zip — but it could be a redirect to the “latest” version of the zip.

we are not validating that it has .zip, but should look for https or http before the button enables (and give error messages - please check URL)

**Comment by rmglennon** [comment]
Closing this one in favor of #216
