### ISSUE TITLE
Step 2: If user deselects all operators, they will get a border to indicate error with a message

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#175]
- Make the next button stay and disable
- Make error message "Please select at least one operator to continue" 
- Use a tint of transitland logo orange for warning state

**Comment by meghanhade** [comment]
@hanbyul-here, the error message is added, and the next button stays. The next button has class "disabled" when no operators are selected, but you can still tab into it and enter-select.

**Comment by meghanhade** [comment]
@hanbyul-here you can work off of branch errorMessage#175
