### ISSUE TITLE
"Which best describes you?" drop-down entry doesn't stick

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#193]
I click an entry in the list of Which best describes you in the "Submit" page of Add a flow, and it doesn't seem to "stick".

To reproduce:
Click the drop-down list
Choose a role
The list contracts, but the answer you picked doesn't appear in the form. 

![image](https://cloud.githubusercontent.com/assets/4380498/12726228/546b4fe8-c8cb-11e5-8ae9-e78e3730636c.png)

**Comment by meghanhade** [comment]
@rhonda, I thought I saw this issue at first, too, but now I'm not able to reproduce. Could you verify that whether it happens every time for you, or only the first time you see the form?

**Comment by meghanhade** [comment]
@rmglennon--ok, so this only happens if you refresh the page, not when you are going through the flow. This happens because when you refresh, your local data is cleared. I'll create a separate ticket to make sure refreshing takes you back to the beginning of the flow.

**Comment by rmglennon** [comment]
Ah, I think you're right @meghanhade. I got into this because I clicked the terms of service link. It opened in the same browser tab (which was unexpected when it had the little box icon), so I had to press Back to get to the form again.

**Comment by rmglennon** [comment]
And this got me into a state where I clicking the Submit Feed button does nothing, either...

**Comment by meghanhade** [comment]
@rmglennon good catch! The terms page should open in a new window, otherwise it throws off the way we set up/clear data models.

**Comment by meghanhade** [comment]
@rmglennon right, it can't submit because the feed model doesn't exist after reloading.
