### ISSUE TITLE
"add a feed" local models are cleared out before changeset submission complete

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#198]
Looks like the reason why @rmglennon isn't getting e-mail notifications is because changesets aren't being fully sent to the server.

https://github.com/transitland/feed-registry/blob/master/app/feeds/new/submit/controller.js#L28 clears out the local models while the changeset is still being sent to the server, before the promise is fully resolved.

@meghanhade I recommend either:

- moving the `unloadAll()` into the `then` block on the promise (which happens after successful post'ing of the changeset).
- or move the `unloadAll()` call to the `feeds/new/success` route

**Comment by meghanhade** [comment]
@drewda I think this should fix that--please check out this PR https://github.com/transitland/feed-registry/pull/199

**Comment by drewda** [comment]
@meghanhade :+1:
