### ISSUE TITLE
Reduce the width of the steps and add more space between each

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#203]
WHAT I DID:
.add-feed-tabs-9e214801 .add-feed-nav .tab.current {
width: 9%
margin: 0px 0px 0px 40px

![screen shot 2016-02-02 at 4 07 04 pm](https://cloud.githubusercontent.com/assets/6125224/12764312/05b34084-c9c7-11e5-999a-d342615cc4c8.png)

**Comment by hanbyul-here** [comment]
did you test it with smaller screen too?

**Comment by souperneon** [comment]
discussed making it not scaling responsive based on large desktop. Maybe try making it a comfortable fixed width.
