### ISSUE TITLE
Submit step edits

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#207]
Move submit button to right and add back button

![screen shot 2016-02-02 at 4 24 55 pm](https://cloud.githubusercontent.com/assets/6125224/12764841/c566153a-c9c9-11e5-81c3-023c2077bc4a.png)

**Comment by drewda** [comment]
@hanbyul-here @souperneon as part of this ticket (or another one), please change the link text from "terms of service" to "contributor agreement"
