### ISSUE TITLE
Error/warning message style consolidation

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#213]
- @hanbyul-here made this for step 3: operators. Use same styling for all errors/warnings
- For step 3: operators, change the message from warning to error (aka red)

@meghanhade working on functionality here https://github.com/transitland/feed-registry/issues/211

**Comment by hanbyul-here** [comment]
you are talking about step 2?

**Comment by souperneon** [comment]
mostly. but making the same styles across the whole flow, so step 1 and 2
