### ISSUE TITLE
focus on first field in form for each step

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#227]

**Comment by meghanhade** [comment]
@souperneon currently, the URL field is in focus when you start the flow. Do you think the first field of the form should have focus for each step?

**Comment by hanbyul-here** [comment]
I put autofocus of url field in this commit : https://github.com/transitland/feed-registry/blame/master/app/feeds/new/index/template.hbs#L35
I think it helps people especially on very first page to get started. For other pages, I wasn't sure so I just left it as they are

**Comment by souperneon** [comment]
That will be really nice if we can :)
Except for the license step, yes?
