### ISSUE TITLE
use API keys to make more requests per second

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#256]
Can use the same keys as Dispatcher:

- https://github.com/transitland/dispatcher/blob/master/config/environment.js#L59
- https://github.com/transitland/dispatcher/blob/master/config/environment.js#L65

And can use the same approach to inject the key into GET requests: https://github.com/transitland/dispatcher/blob/master/app/application/adapter.js#L27

**Comment by meghanhade** [comment]
Encountered some issues last week, trying a new option in the adapter.
