### ISSUE TITLE
pagination allows offset larger than total number of operators

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#259]

**Comment by drewda** [comment]
@meghanhade have a look at the fix I just put into Dispatcher: https://github.com/transitland/dispatcher/pull/25 It will probably solve your problem in Feed Registry, too.

**Comment by meghanhade** [comment]
@drewda I used your Dispatcher approach here: PR https://github.com/transitland/feed-registry/pull/271.

**Comment by drewda** [comment]
:+1:
