### ISSUE TITLE
Pagination: scroll to top with results page change

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#267]
Set up listener on query params to trigger scroll to top.

**Comment by meghanhade** [comment]
@drewda This solution appears to work for the offset and the add-a-feed flow. Would you please review the pr https://github.com/transitland/feed-registry/pull/270?

**Comment by drewda** [comment]
@meghanhade looks good!

**Comment by meghanhade** [comment]
@drewda ok, thanks for checking!
