### ISSUE TITLE
Pagination: return 404 page sometimes

### ISSUE THREAD

**Issue by hanbyul-here** [transitland/feed-registry#281]
Idk why, but navigating through nex/previous button returns 404 page sometimes

**Comment by drewda** [comment]
@hanbyul-here can you open developer console and look for errors?

(If it's a 429 error, that means too many requests to server, so we should increase the limits.)

**Comment by hanbyul-here** [comment]
it is hard to reproduce the error :( I will when I face the error again

**Comment by drewda** [comment]
Doesn't seem like this has reoccurred, so I'll close.

@hanbyul-here do feel free to reopen if you notice the problem again.
