### ISSUE TITLE
filter operators by feed-import level

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#290]
The list of operators is getting unwieldy. Let's allow users to filter down the list by feed import level.

**Comment by meghanhade** [comment]
@souperneon, do you want to think about where these should go? would you like to create basic mocks?

**Comment by souperneon** [comment]
I had mocked up filters when we first started designing the registry. I'll find those and ATT hdf them here for discussion. Are you working on this now @meghanhade?

**Comment by meghanhade** [comment]
Thanks @drewda. I'd like to get this going this week, after adding existing feed/operator feedback.

**Comment by drewda** [comment]
:+1:

**Comment by meghanhade** [comment]
We also should be able to filter by import level

**Comment by souperneon** [comment]
Talked to @meghanhade - We decided to start with geographic filtering.
v1- Open search box that the user can search country, state/province/region and select any one (checkboxes for multiple selection can happen for v2)

![transitland_feedfilter_1 1](https://cloud.githubusercontent.com/assets/6125224/13930666/4053d094-ef76-11e5-90f1-393c50725eed.png)
![transitland_feedfilter_1 2](https://cloud.githubusercontent.com/assets/6125224/13930665/40537d92-ef76-11e5-87a1-875dfd7f5460.png)

**Comment by drewda** [comment]
@souperneon @meghanhade let me suggest that you implement `import_level` filtering first. It will be useful to be able to show which feeds are routable. Also, it will be easier to implement, since it's a fixed list of import levels (vs. the dynamic list of countries, states, metros--which will probably need a small API addition so you can get a complete list).

**Comment by meghanhade** [comment]
@drewda sure, we can start there :+1:  (I saw that on the mobility launch checklist today, but Ekta and I didn't know about the idea to filter by import_level when we talked last week.)

**Comment by drewda** [comment]
Filtering by `import_level` on operators will depend on a back-end addition that @irees is working on: https://github.com/transitland/transitland-datastore/issues/472

**Comment by meghanhade** [comment]
Filtering by import_level is set up, pending this fix: https://github.com/transitland/transitland-datastore/issues/537

**Comment by meghanhade** [comment]
https://github.com/transitland/transitland-datastore/issues/537 has been resolved.

@irees will resolve https://github.com/transitland/transitland-datastore/issues/540 which is causing some filtering problems.

**Comment by meghanhade** [comment]
Discussed UI elements with @souperneon that will let user know they are seeing a filtered list, with breadcrumb to view entire list.
