### ISSUE TITLE
filter operators by region, state, and/or country

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#309]
Allowing user to filter by region, state/province, and/or country would probably be sufficient.

At the same time, might be worth thinking about showing the totals within each region, state/province, and country. (For example, a drop-down select could list "United States (50)" assuming there are 50 feeds in the US.)

Unlike Playground, I'd suggest allow user to independently filter. So they could see a drop-down of all the regions in the world, without having to drill-down first by country. That would let them browse DC metro area, which cuts across DC, Virginia, and Maryland.

^^ @souperneon and @meghanhade some ideas for filtering. Feel free to consider alternatives.

**Comment by meghanhade** [comment]
Allowing user to filter by region, state/province, and/or country would probably be sufficient.

At the same time, might be worth thinking about showing the totals within each region, state/province, and country. (For example, a drop-down select could list "United States (50)" assuming there are 50 feeds in the US.)

Unlike Playground, I'd suggest allow user to independently filter. So they could see a drop-down of all the regions in the world, without having to drill-down first by country. That would let them browse DC metro area, which cuts across DC, Virginia, and Maryland.

**Comment by drewda** [comment]
Depends on https://github.com/transitland/transitland-datastore/issues/549 on the back-end
