### ISSUE TITLE
Add Edit button to the feed details page

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#321]
If you step through the Add a feed flow and enter the URL of a GTFS feed that is already in the feed registry, you are put into a mode where you can edit the feed details. It's a little awkward, but here's the way we documented this: https://transit.land/documentation/feed-registry/edit-a-feed.html

What if we added an Edit button in the Feed Details section (example page: (for example: https://transit.land/feed-registry/operators/o-9q9-actransit)? 

If the button said "Edit" or "Edit feed details", it should be clear that you are editing the metadata, and not the contents of the actual GTFS file.

As part of this, we could also remove the "If you notice an error, please email us..." line. We've gotten a few people contacting us to change the feed details, so this would be a self-service way for the users to create a changeset.

Suggestions:
- [x] Add Edit button to feed details
- [ ] Provide way to update the URL for a GTFS feed data location (if you replace the URL in the add a feed flow, you may get into a scenario where duplicated feed entries are created)
- [x] Remove "If you notice an error, please email us..." line

**Comment by drewda** [comment]
@rmglennon this sounds great. Thanks for considering in depth, and also typing up instructions for how users can do this manually in the meantime.

I can try implementing your first and last suggestions. Editing the URL may be more problematic. Worst case, to edit the URL will require manual intervention but we'll be able to have an easier flow for every other type of change.
