### ISSUE TITLE
Add filter by operator name

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#322]

**Comment by meghanhade** [comment]
Query params for place and name filters are not clearing when returning to index. This affects the behavior when you click on an operator name to view the feed details. (It takes two clicks to click through.)

**Comment by meghanhade** [comment]
1) don't render list until use types
2) search bar goes away after selection
3) square corners
4) smaller size

**Comment by drewda** [comment]
@meghanhade filtering by place is most important; if search by name is proving problematic, do feel free to drop or defer it.
