### ISSUE TITLE
Add link to routable feeds on "all operators" view

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#355]

**Comment by drewda** [comment]
After @meghanhade  and I chatted last week, we agreed that feed import-level filtering is best kept as a hidden feature, only available to users linking in from off-site. For example, from one of the transit-routing blog posts on mapzen.com.

In the future, let's find a place on mapzen.com to list routable coverage area in an attractive interface, along with Kevin's "transit island" routing coverage map. Even if the import-level attribute technically lives within the Transitland Datastore (for the sake of implementation expedience), it's more to do with the Mapzen-branded Turn-by-Turn product.

Who knows, in the future, it would be great if another organization's routing engine also consumed its source data from Transitland.

//cc @burritojustice
