### ISSUE TITLE
switch copy to use "metro" (rather than "region")

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#356]
In Datastore API JSON responses, we refer to an operator's locality as "metro." Also, as @stevevance pointed out on https://github.com/transitland/transitland/issues/67, "region" can sometimes be used to refer to the same administrative level as "state" or "province" So, let's just standardize on using "metro."

@meghanhade and @rmglennon sounds reasonable to you two?

Places that could use updates:

![feed registry transitland 2016-07-18 18-12-47](https://cloud.githubusercontent.com/assets/212369/16935320/3f73ff00-4d13-11e6-89d0-7bcd739b8482.png)

![feed registry transitland 2016-07-18 18-13-06](https://cloud.githubusercontent.com/assets/212369/16935328/4af9efe2-4d13-11e6-8f86-987a01bd0430.png)

![feed registry transitland 2016-07-18 18-14-07](https://cloud.githubusercontent.com/assets/212369/16935343/788b3114-4d13-11e6-9613-b6a1cc5eff79.png)

At the same time as changing the language, it's also worth removing the "(optional)" text on the operator form. It's useful for contributors to include that info.

**Comment by stevevance** [comment]
I wanna upvote this.
