### ISSUE TITLE
Pages should have unique titles

### ISSUE THREAD

**Issue by stevevance** [transitland/feed-registry#366]
Each page should have a unique `<title>` to assist with identifying different pages in a browser history and within bookmarks. 

This is what it currently looks like:
![pasted_image_at_2016_10_14_11_38_am_720](https://cloud.githubusercontent.com/assets/1330459/19395796/25b147da-9205-11e6-8bf6-fa03e0aa600f.png)

**Comment by drewda** [comment]
Finally added in #402

**Comment by stevevance** [comment]
Hurray!
