### ISSUE TITLE
How can we get bigger rate limit?

### ISSUE THREAD

**Issue by dmitrykinakh** [transitland/feed-registry#398]
We are building real estate project and want to have transit data from transit.land integrated into our app. But we are faced that we are not able to that since after doing ~ 600-800 requests we got rate limit error.

We are trying to load the data for whole FL state in the USA (system, routes, stops and stops types)

What are required steps to avoid that limit?

**Comment by drewda** [comment]
@dmitrykinakh Transitland is currently run on donated servers and has constrained resources. Unfortunately, everyone has to stay within the rate limits for now.

Here are two ways to work within the rate limits:
- whenever your code detects a `429 Too Many Requests` response, retry the request after a delay. One technique for doing this is called "exponential backoff"
- revise your code to limit its requests to a max of 6 per second (the Transitland API rate limit). Many HTTP request libraries have a throttling mechanism.

I'll close this issue now, but do feel free to reopen if you have further questions
