### ISSUE TITLE
Not possible to get New York data (stop times) due 504 error

### ISSUE THREAD

**Issue by dmitrykinakh** [transitland/feed-registry#399]
I'm integrating transitland feeds into own app and for New York state after offset=5784000 for stop times dataset I'm starting receiving 504 HTTP error. Is there a way how I can avoid this? API request that doesn't work for me is located below.

https://api.transit.land/api/v1/schedule_stop_pairs?offset=5784000&per_page=1&operator_onestop_id=o-dr5r-nyct 

An image that explains the issue:
![image](https://user-images.githubusercontent.com/8025637/39464398-affdbbe4-4d25-11e8-8583-def1a36faefd.png)

**Comment by irees** [comment]
Hi @dmitrykinakh 

For paging through large result sets, there is a `sort_min_id` query parameter that has better performance. When `sort_min_id` is used the pagination links will include the link to the next page.

https://api.transit.land/api/v1/schedule_stop_pairs?sort_min_id=3559561356&per_page=1&operator_onestop_id=o-dr5r-nyct
(this is the record with offset=5784000).
