### ISSUE TITLE
functionality to turn on/off operators when there are multiple operators in a feed

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#82]
@souperneon's existing mocks show state for operator that is selected to be included, but not state for an operator that is being excluded:

![transitland_upload_2 5](https://cloud.githubusercontent.com/assets/212369/12273446/db4122ec-b933-11e5-9924-710e89edda1e.png)

**Comment by souperneon** [comment]
I imagined it to be that checkbox (currently checked and green) 
Default: All operators selected
User can uncheck to not add an operator.

**Comment by meghanhade** [comment]
@souperneon, could you provide a mock showing what you'd like it to look like when an operator is de-selected?

**Comment by souperneon** [comment]
Can we just use a default checkbox? That's what I was intending. I super designed it but it's important for v1 that it look like that

**Comment by meghanhade** [comment]
@drewda, do you want to review this PR? https://github.com/transitland/feed-registry/pull/110

**Comment by drewda** [comment]
@meghanhade sure!
