### ISSUE TITLE
improve timezone field

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#83]
- [ ] populate timezone options for places other than US
- [ ] @souperneon redesign or find another app that has a usable and attractive timezone dropdown-select

**Comment by souperneon** [comment]
Are we going to have a full list like this? > https://www.wikiwand.com/en/List_of_UTC_time_offsets

Ideally, we should try to populate this field if we have any other location field (which can serve as a starting suggestion and one less field for the user to fill out) So if the feed is from *New York, USA* we know that it is *GMT -5:00 US/New York*

I found this plugin which is US only but maybe we can extend it?
http://www.jqueryscript.net/demo/Easy-Timezone-Picker-with-jQuery-Moment-js-Timezones/ 

This discussion is around the UX for timezone pickers is pretty good: http://ux.stackexchange.com/a/21417

For the design, I still think Sunrise (https://calendar.sunrise.am) or even Google Calendar app on iOS is pretty good

**Comment by drewda** [comment]
Good realization on our call: timezone is required, so no need to ask users. https://developers.google.com/transit/gtfs/reference?hl=en#agencytxt

**Comment by meghanhade** [comment]
I'm going to remove the timezone field and move the website field to the top row.
