### ISSUE TITLE
loading and error states during/after FeedInfo polling

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#84]

**Comment by souperneon** [comment]
Can I see a sample implementation for this on the front end?

**Comment by rmglennon** [comment]
Perhaps the feed scanning process could use something like a progress indicator or wait cursor to give a visible indicator of status? Loading happens silently now.

**Comment by meghanhade** [comment]
Yep, we're working on this. There's a conflict between how we're clearing out the local datastore and the promise that gets returned indicating the loading/error state.

**Comment by drewda** [comment]
@meghanhade if you want to use the same spinner as the one @hanbyul-here created for Playground, I copied that code into an Ember component for the Dispatcher app.

Code at https://github.com/transitland/dispatcher/tree/master/app/components/loading-spinner

And you can see it in action at: https://transit.land/dispatcher/feeds

**Comment by souperneon** [comment]
yeah, it will be good to have both ultimately. The loader/spinner and error states.
Hopefully, the processing time is short and you never have to see the loader/spinner but it should be in there just in case.
