### ISSUE TITLE
break license step into multiple substeps

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#85]
previous discussion and animated gif: https://trello.com/c/WjIoiG6p/501-feed-registry-add-a-feed-break-license-step-into-smaller-sub-steps

**Comment by drewda** [comment]
one possible approach: https://github.com/transitland/feed-registry/pull/80

**Comment by meghanhade** [comment]
What do we mean by "can you read and interpret"? Are we asking if the submitter is willing to do so, or are we asking if the license is legible? (I realize this copy is a work in progress, but I'm thinking about what we're asking with regard to the UI flow.)

https://github.com/transitland/feed-registry/blob/drew/license-substeps/app/feeds/new/license/template.hbs#L33

**Comment by drewda** [comment]
@meghanhade the former (if the user is willing to do so) makes sense to me. Does that fit with the beta test feedback in terms of only some users feeling equipped to interpret licenses?
