### ISSUE TITLE
Google Analytics tracking for "add a feed" flow

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#89]

**Comment by meghanhade** [comment]
@drewda what's a good deadline for this? Have we decided on a launch date?

**Comment by drewda** [comment]
@meghanhade let's all chat about launch date in our product meeting tomorrow (and I'm glad to chat one-on-one in the meantime).

**Comment by meghanhade** [comment]
Google Analytics is already set up to track any "didTransition" action on the entire Feed Registry App. This means anytime the route changes, as it does with each step of the Add a Feed flow, Google Analytics captures that.
