### ISSUE TITLE
reduce payload size & improve load time

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#94]
http://dev.transit.land/feed-registry/assets/vendor.js clocks in at 3.5Mb. All of that has to be loaded before user sees anything appear on the screen.

Some strategies to try before we launch this on production:

- [x] remove any unnecessary JavaScript/Bower packages (moment-timezone? Bootstrap icons? font-awesome?)
- [x] move header/nav bar into `index.html` so something will appear before Ember is fully loaded and ready to render a template 
- [ ] have country-state selector fetch state lists by AJAX (rather than baking all of it into the app payload) #232 
- [ ] follow advice from Google PageSpeed Insights: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ftransit.land%2Ffeed-registry
- [ ] make sure S3 and proxies are setting proper cache headers
- [x] make sure S3 and proxies are sending gzip'ed HTTP responses
- [x] serve assets from CDN
- [ ] consider adding http://pathgather.github.io/please-wait/

**Comment by drewda** [comment]
@baldur @heffergm thoughts on the latter three items?

**Comment by heffergm** [comment]
S3 itself doesn't do on the fly compression/decompression. You could upload compressed assets and mark them 'Accept-Encoding: gzip' in the metadata, but any client that can't accept that is just going to get data back.

But this is neither here nor there... right now, the setup is such that in prod, all the compression setting is being handled in APIAxle:

https://github.com/mapzen/chef-mapzen_apiaxle_custom/blob/master/templates/default/transitland.include.erb#L1

All the types you see listed with return compressed if the client is sending Accept-Encoding: gzip (I just added `application/javascript`.

`curl -v -H "Accept-Encoding: gzip" "https://transigistry/assets/vendor.js"`

vs

`curl -v "https://transigistry/assets/vendor.js"`

We would need to set up either cloudfront or fastly if we want to implement

**Comment by drewda** [comment]
Sounds useful to add either Cloudfront or Fastly. We can easily have Ember CLI put in the right asset fingerprints and domain (http://ember-cli.com/asset-compilation/).

@heffergm have a preference for one or the other?

**Comment by heffergm** [comment]
@drewda sorry, my previous comment seems to have been truncated which may have made it a little less than clear (I updated the closing comment). To clarify:

- all your assets should be being returned as gzip'd provided the client is sending Accept-Encoding: gzip which just about everything should be doing these days.

- if we really feel there's a need for a CDN, we need some more information, (and you're going to want to make sure you have a means of expiring content without explicitly making cache purge requests (like putting assets in date stamped directories)

- are we talking about trying to drop the entire site behind the edge, or do you want to update your code to reference a CDN distribution URL directly for assets (which I think is perhaps what you were referring to with Ember; apologies, not familiar and haven't had a chance to read it). If you just need a CDN distribution URL to reference assets with, it's trivial. If we move the entire site behind the edge, we'll need to talk as it involves a bit of a migration and cost.

**Comment by drewda** [comment]
Thanks for the details, @heffergm 

Great that everything is going out gzip'ed.

As a next step, CDN for assets (JS, CSS, images) would be helpful. We can keep all HTML in its current location. We can use Ember's build tooling to add timestamps/versions/hashes to all the asset URLs.

Can CloudFront deploy from subdirectories of the existing S3 `transit.land` and `staging.transit.land` S3 buckets? (I'm unfamiliar with how CloudFront works.)

**Comment by heffergm** [comment]
I can provide you with an URL that is a front for the content of the existing buckets, yes.

**Comment by drewda** [comment]
O.K., sounds straightforward.

**Comment by heffergm** [comment]
Production: d11xhlzkgsq6oc.cloudfront.net
Dev: d2tkmr00hnrtoq.cloudfront.net

Example: https://d11xhlzkgsq6oc.cloudfront.net/assets/test-support.js

I've gone ahead with cloudfront rather than fastly because your buckets contain dots in them (e.g. transit.land), which means that we can't access them as unique origins because they appear as subdomains to AWS (https://transit.land.s3.amazonaws.com for example is not happy).

Moving the buckets to something like transitland and transitland-dev would resolve the problem and we could use Fastly. That said, I think for this use case, it's neither here nor there.

cc @baldur ^

**Comment by drewda** [comment]
@heffergm CDN is working well on staging now. Thanks again.

**Comment by drewda** [comment]
Probably have made enough performance improvements for now.

Some future follow up:
- have country-state selector fetch state lists by AJAX #232 
- @meghanhade and @hanbyul-here can evaluate using https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ftransit.land%2Ffeed-registry
