### ISSUE TITLE
style button and copy that leads into "add a feed"

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#95]
Right now we have a placeholder button at the bottom of http://dev.transit.land/feed-registry/

Let's replace "If you would like to add a feed (or if you notice an error in an existing entry) please email us at transitland@mapzen.com." with the button.

@souperneon thoughts on styling?

**Comment by rmglennon** [comment]
:+1: I had that line scratched out in my notes.

**Comment by drewda** [comment]
mock for styling: https://github.com/transitland/feed-registry/issues/105
