### ISSUE TITLE
what happens to submitted feeds and operators at conclusion of "add a feed" flow?

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#96]
When a user currently completes the "add a feed" flow, the new feed and operator models stay in the local Ember Data store. They'll appear in the operators table, until the user presses reload or leaves the Feed Registry.

Is this the behavior we want? If so, should we style the local feeds/operators differently, so it's clear that they are proposed? If not, we should clear the local models after submission, and use copy to explain that it's been submitted for review.

Off the top of my head, I think the latter makes more sense. But what do you think @meghanhade and @souperneon?

**Comment by meghanhade** [comment]
I agree that the latter makes more sense here, @drewda. I do think it's important for people to see the feed they just submitted (in a way that the feed is under review), but I don't think that should happen in a way that will disappear once they've left the page/reloaded.

**Comment by rmglennon** [comment]
I liked @meghanhade's suggestion of adding "What happens now?" to the page and some information about contacting the submitter (method and timeline of contact to be determined).

Current UI text: "Thank you for adding a feed! We have created a changeset to review on Transitland." 

Suggesting something like: 

Thank you for submitting a feed to Transitland! 

Next, your feed will be reviewed and imported. Occasionally, there are issues with the import process that could cause a delay or make the feed unsuitable for posting on Transitland.

If you provided your contact information, you will be notified when your feed is part of the Transitland feed registry.

**Comment by souperneon** [comment]
This is a big big improvement! Just to clarify, if there is an issue in the import process do we contact the contributor? If we do, we should add that at the end of the second para. Right now it kinda sounds like if there is an issue with the import process nothing will end up happening

**Comment by drewda** [comment]
At this point, I think the simplest approach will be to use the "success" page to give the information about the process. The local feed and operator models can either be cleared out when the user lands on the success page, or as they're transitioning back to the Feed Registry index. In either case, it's simplest to have the local models gone before the user sees the index again.

**Comment by souperneon** [comment]
Sounds good. One more note @rmglennon, should Feed Registry be in title case?

**Comment by meghanhade** [comment]
@drewda and I will test that local data is deleted at the end of the add-a-feed flow

**Comment by souperneon** [comment]
Copying from Rhonda's comment:

Thank you for submitting a feed to Transitland!

Next, your feed will be reviewed and imported. Occasionally, there are issues with the import process that could cause a delay or make the feed unsuitable for posting on Transitland.

If you provided your contact information, you will be notified when your feed is part of the Transitland Feed Registry.

**Comment by meghanhade** [comment]
Note to self (and cc @drewda): The submission does show up in the Feed Registry when the user follows the "return to feed registry" link at the bottom of the success step. It does not show up in the FR upon refresh, or when navigating through the header menu to the FR. I'll need to clear out the operators when the success step link is used.

**Comment by drewda** [comment]
@meghanhade :+1:
