### ISSUE TITLE
after tabbing into country/region fields, open drop-down select

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#97]
This way a user can complete the entire form by advancing from field to field by pressing <kbd>tab</kbd>.

@meghanhade have a look at the `onfocus` action example at: http://www.ember-power-select.com/docs/action-handling

(Looks like it's not yet possible to have the user select the highlighted option and advance to the next field, all in one go, by pressing <kbd>tab</kbd>: https://github.com/cibernox/ember-power-select/issues/20 But it is possible with two key presses: <kbd>enter</kbd> to select, followed by <kbd>tab</kbd> to advance.)

**Comment by meghanhade** [comment]
@drewda the ember-power-select site seems to be broken.
