### ISSUE TITLE
Add Feed - minor suggestions to UI text for the steps

### ISSUE THREAD

**Issue by rmglennon** [transitland/feed-registry#99]
Here are a couple of suggestions for the steps for adding a feed, mostly to make them consistent to be all nouns or all starting with verbs (other than Submit). I think the only one that has to change is upload, as this could suggest that you are browsing to a file. 

Current --> Suggestion as a noun (starting with a verb)
1. Upload feed --> Feed URL (Specify feed)
2. Add operator(s) --> Transit operators (Review transit operators)
3. License info --> License (Add license)
4. Submit

**Comment by rmglennon** [comment]
Another idea. Is there a step 5 for "Completed" or "Done" or "Finished" or "Submitted"? Rather than change the header on the page to SUCCESS!, perhaps it stays as ADD A TRANSIT FEED with an additional step that shows the confirmation that the feed is in review?

**Comment by rmglennon** [comment]
Update: following the front-end meeting on 1/21/16, we were going to think more on these headings in the wizard. We did decide that there should not be a step 5 -- the success page should take you to a new page that would look different from the others (like confirming an online order shows a new page).

Some liked verbs for the headings.
1. Specify feed
2. Review transit operators
3. Add license
4. Submit

PR #143 addresses most of the UI suggestions for the add a feed flow, but not these overall heading names.

**Comment by souperneon** [comment]
Suggestions - 
1. Specify feed (specify feels a little harsh I feel) 
2. Review transit operators - Review Operators
3. Add license - Good
4. Submit - Good

**Comment by rmglennon** [comment]
@souperneon @meghanhade for specify in the paragraph, we went back to "find". Is that preferred for the heading?

**Comment by rmglennon** [comment]
Feed
Operators
License
Submit

**Comment by souperneon** [comment]
https://github.com/transitland/feed-registry/issues/164
